### ISSUE TITLE
FYI works on keycloak 16

### ISSUE THREAD

**Issue by labeneator** [d4rkstar/kong-konga-keycloak#13]
FYI, this tutorial works well with keycloak 16.xx. keycloak 17 responds with an error  on any of the openid urls

```
GET /auth/realms/experimental/.well-known/openid-configuration HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: xxxxxx
User-Agent: HTTPie/0.9.8



HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 149
Content-Type: application/json
Date: Sun, 13 Feb 2022 11:26:44 GMT
Referrer-Policy: no-referrer
Server: nginx/1.14.2
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

{
    "error": "RESTEASY003210: Could not find resource for full path: https://xxxxx/auth/realms/experimental/.well-known/openid-configuration"
}
```

**Comment by d4rkstar** [comment]
Hello,
it seems that in keycloak 17 the /auth part in the url is not used anymore.

Path should be: https://xxxxx/realms/experimental/.well-known/openid-configuration

And this should be updated in oidc configuration and in all requests.

I'm releasing an update this evening.

**Comment by d4rkstar** [comment]
Resolved by [6352b43](https://github.com/d4rkstar/kong-konga-keycloak/commit/6352b435e19db4a6debf939b4e62f0639d84bc41). Let me know

**Comment by labeneator** [comment]
Bump the installed version at the top of readme.md to reflect the version changes. Otherwise, LGTM

```
Installed versions

Kong 2.0.4 - alpine
Konga 0.14.7
Keycloak 10.0.2
```

**Comment by labeneator** [comment]
Tested the tutorial against keycloak-17.0.0 and confirmed that it works.

**Comment by d4rkstar** [comment]
> Bump the installed version at the top of readme.md to reflect the version changes. Otherwise, LGTM
> 
> ```
> Installed versions
> 
> Kong 2.0.4 - alpine
> Konga 0.14.7
> Keycloak 10.0.2
> ```

Updated with latest versions. Thank you for reporting.

B.
