### ISSUE TITLE
kong container cannot get running

### ISSUE THREAD

**Issue by ArliasX** [d4rkstar/kong-konga-keycloak#4]
On docker-compose up the kong container doesn't get running and stops with the following error:

2020/10/13 21:50:18 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:16: Database needs bootstrapping or is older than Kong 1.0.,
To start a new installation from scratch, run 'kong migrations bootstrap'.,
To migrate from a version older than 1.0, migrated to Kong 1.5.0 first. ,
If you still have 'apis' entities, you can convert them to Routes and Services,
using the 'kong migrations migrate-apis' command in Kong 1.5.0.,
stack traceback:,
	[C]: in function 'error',
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:16: in function 'check_state',
	/usr/local/share/lua/5.1/kong/init.lua:392: in function 'init',
	init_by_lua:3: in main chunk,
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:16: Database needs bootstrapping or is older than Kong 1.0.

**Comment by d4rkstar** [comment]
Hello @ArliasX, it seems that the database was not bootstrapped.

Try to do the following:

1. Stop kong - docker-compose stop kong
2. Ensure that the kong-db is running - docker-compose ps kong-db (you should see a pod in state Up)
3. If kong-db is not running, start it - docker-compose up -d kong-db
4. Run migrations - docker-compose run --rm kong kong migrations bootstrap
5. Start kong - docker-compose up kong 

The error should be gone.

**Comment by ArliasX** [comment]
ok yes it works, thanks guys!!!
