### ISSUE TITLE
Adding Monitoring tools 

### ISSUE THREAD

**Issue by issambaccouch** [d4rkstar/kong-konga-keycloak#9]
this repository is great but it can be more greater with monitoring tools like Prometheus with Grafana dashboard , any plan to add those tools in future ?

**Comment by d4rkstar** [comment]
Hello @issambaccouch! Thank you for your feedback.

At this time i've no plan to add monitoring tools, as this tutorial covers only token introspection.

However, you can send some PR: i will be happy to review and merge!

**Comment by issambaccouch** [comment]
@d4rkstar I added a new commit implementing those tools.
https://github.com/d4rkstar/kong-konga-keycloak/pull/15/commits
